[package]
name = "e57-python"
version = "0.1.0-a5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "e57"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
e57 = "0.10.2"
numpy = "0.20.0"
ndarray = "0.15.6"
